### ISSUE TITLE
i want to record voice for enunu

### ISSUE THREAD

**Issue by SCERYP** [oatsu-gh/ENUNU#1]
i want to record russian voice for enunu 
how to do it?

**Comment by oatsu-gh** [comment]
Hi, thank you to have interest in ENUNU.
ENUNU uses singing-model generated with NNSVS(https://github.com/r9y9/nnsvs), and NNSVS needs singing-voice-database (like kiritan-singing or ofuton-p-singing) to generate a singing-model.

See NNSVS's issue (https://github.com/r9y9/nnsvs/issues/22) about making your own singing-model. 

I reccomend try to generate singing-model from existing singing-voice-database, prior to try make your singing-voice-database.

As summery, to make enunu voice by step,
① make a singing-voice-database
② generate singing-model using NNSVS
③ configure the singing-model settings for ENUNU

**Comment by Sceryp** [comment]
> Hi, thank you to have interest in ENUNU.
> ENUNU uses singing-model generated with NNSVS(https://github.com/r9y9/nnsvs), and NNSVS needs singing-voice-database (like kiritan-singing or ofuton-p-singing) to generate a singing-model.
> 
> See NNSVS's issue ([r9y9/nnsvs#22](https://github.com/r9y9/nnsvs/issues/22)) about making your own singing-model.
> 
> I reccomend try to generate singing-model from existing singing-voice-database, prior to try make your singing-voice-database.
> 
> As summery, to make enunu voice by step,
> ① make a singing-voice-database
> ② generate singing-model using NNSVS
> ③ configure the singing-model settings for ENUNU

The problem is that I have absolutely no idea how NNSVS works.
There is no information on the Internet How to create a voice for NNSVS.
I do not understand the technology
There is no remclist nnsvs on the Internet
Most people do not understand how to download, How to work with NNSVS or how to make a voice for NNSVS

**Comment by Sceryp** [comment]
> Привет, спасибо за интерес к ENUNU.
> ENUNU использует певческую модель, созданную с помощью NNSVS ( https://github.com/r9y9/nnsvs ), а NNSVS нуждается в базе данных певческого голоса (например, киритан-пение или офутон-п-пение) для создания певческой модели.
> 
> См. Выпуск [NNSVS](https://github.com/r9y9/nnsvs/issues/22) ( [r9y9 / nnsvs # 22](https://github.com/r9y9/nnsvs/issues/22) ) о создании собственной певческой модели.
> 
> Я рекомендую попытаться сгенерировать певческую модель из существующей базы данных певческого голоса, прежде чем пытаться создать свою базу данных певческого голоса.
> 
> Вкратце, чтобы сделать голос enunu шаг за шагом,
> ① создайте базу данных певческого голоса
> ② сгенерируйте певческую модель с помощью NNSVS
> ③ настройте параметры певческой модели для ENUNU

Could you please explain to me how to make a voice for NNSVS

**Comment by nagotown** [comment]
NNSVS does not use a reclist. you use recordings of yourself singing songs. after you have all your singing data, you label the song file for the phonemes, essentially an oto for ai voicebanks. there is not currently support for russian as far as i know. but they already provided you info, and you can get answers on google. if you can't find any results, you aren't searching the right thing.
