### ISSUE TITLE
Is it possible to include other vocoder, such as WaveNet?

### ISSUE THREAD

**Issue by YellowLime77** [oatsu-gh/ENUNU#11]
Just as the title says, I'm wondering if the code can be modified to use other vocoders, like the neural WaveNet vocoder. If so, steps could be provided which could really help me out, as even with a dataset with good quality and quantity of files, the final result always seems robotic, which I believe is because of the vocoder. Therefore, neural network vocoders could maybe produce better results.

Thank you so much!

(Also posted at https://github.com/r9y9/nnsvs/issues/72)

**Comment by oatsu-gh** [comment]
Hi, Lime!
It get possible to use and to build on ENUNU another vocoder when the vocoder released on NNSVS.

**Comment by YellowLime77** [comment]
Thanks for the response! I'll try implementing another vocoder for now, and I'll close the issue.
