### ISSUE TITLE
Support for neural vocoders (NSF, Parallel WaveGAN)

### ISSUE THREAD

**Issue by JellyBrick** [oatsu-gh/ENUNU#18]
`NNSVS` now supports `Parallel WaveGAN` and `NSF`.
Is it possible to use these vocoders on `ENUNU`?

# Related pages

- https://github.com/nnsvs/nnsvs/blob/master/docs/train_vocoders.rst
- https://github.com/nnsvs/nnsvs/issues/72
- #11

**Comment by oatsu-gh** [comment]
Hi! 
Not impregnated but can be implemented.

**Comment by JellyBrick** [comment]
#20
