### ISSUE TITLE
I need help in knowing details to how to make a voice model

### ISSUE THREAD

**Issue by mona1222002** [oatsu-gh/ENUNU#21]
Hi, I got introduced to nnsvs after trying talknet and asking if there is any way to perform voice synthesis and get a better quality, but I actually need some help in knowing how to make the dataset, so if you can help me by giving me some detailed instructions and telling me what softwares to use to help in creting the dataset, I'll be really thankful

**Comment by mona1222002** [comment]
> Hi, I got introduced to nnsvs after trying talknet and asking if there is any way to perform voice synthesis and get a better quality, but I actually need some help in knowing how to make the dataset, so if you can help me by giving me some detailed instructions and telling me what softwares to use to help in creting the dataset, I'll be really thankful

and can I have English and Korean together in the same dataset and train them together

**Comment by oatsu-gh** [comment]
Hello,


> asking if there is any way to perform voice synthesis and get a better quality
More amount of sample of voices (or songs) that have consistent singing style will provide  better results. Less-noise WAVs are appreciated.

> I actually need some help in knowing how to make the dataset
The following document will be helpful to make datasets.
https://docs.google.com/document/d/1uMsepxbdUW65PfIWL1pt2OM6ZKa5ybTTJOpZ733Ht6s/edit

> what softwares to use to help in creting the dataset
Score: UTAU for UST file, MuseScore for musicxml file. 
LAB: wavesurfer, audacity or oto2lab
WAV: any DAW you like

>  can I have English and Korean together in the same dataset and train them together
Yes but so complicated that I recommend making normal small one at first.
