### ISSUE TITLE
Missing py/modify_full_label_for_enunu.py.

### ISSUE THREAD

**Issue by taroushirani** [oatsu-gh/ENUNU#4]
Hello. I found that there is no py/modify_full_label_for_enunu.py which is called from nnsvs_recipe_for_enunu/ofuton_p_utagoe_db/svs-world-conv/utils/data_prep.py.

**Comment by oatsu-gh** [comment]
nnsvs_recipe_for_enunu に関して、昨年12月頃に作りかけた状態で放置してあります。申し訳ありません。

現在、ステージ0関連のスクリプトは現在 [**py/train**](https://github.com/oatsu-gh/ENUNU/tree/main/py/train) 以下に置いてあります。正常に動作したら nnsvs_recipe_for_enunu のほうに適用します。また、train/py はしばらくの間頻繁に仕様変更すると思いますので、通常のNNSVSモデルを移植するようお願いいたします。その際の学習方法は通常のNNSVSモデル生成で構いません。ただし、モデルに同梱するenuconfig.yaml 中の `trained_for_enunu` を `false` にしてください。

Sorry, nnsvs_recipe_for_enunu/ofuton_p_utagoe_db is not been maintained now. You can use normal NNSVS singing models with ENUNU with no special training but with need to prepare enuconfig.yaml.

**Comment by oatsu-gh** [comment]
Updated the recipe instantly but hed file is not fully optimized.
https://github.com/oatsu-gh/ENUNU/commit/6920391b236295eb0d2a43dccf90180294ce3df0

**Comment by taroushirani** [comment]
Thank you for your rapid response.  I'll follow your recommendations.
