### ISSUE TITLE
I can't use it.

### ISSUE THREAD

**Issue by ffeliph999** [oatsu-gh/ENUNU#7]
does not work on my computer, the ENUNU plugin and also the training kit, probably because my GPU is not NVIDIA, is there any version of ENUNU and its training kit that does not need CUDA?

**Comment by oatsu-gh** [comment]
ENUNU plugin does work  without NVIDIA GPU, and training-kit does, I suppose. I've tried on my laptop.

**Comment by ffeliph999** [comment]
I managed to get the ENUNU plugin to work, even though I don't have an nvidia GPU, but the training kit on my computer is experiencing the problem below
![aaa](https://user-images.githubusercontent.com/90061813/132103184-200622ef-83fc-4230-b269-e7b80512e2c6.PNG)

so I tried using google colab, and training stops in the middle of the process displaying the message     run.sh: line 12: 1160 Segmentation fault (core dumped) $@

**Comment by oatsu-gh** [comment]
The error in the image is from character encodings. Try to changing  PYTHONENCODING to UTF-8 or edit nnmnkwii/io/hts.py so that it decode with UTF-8.

The segmentation fault cannot be solved with my skills, unfortunately. It's probably from pyworld, world or harvest written in C++.
